name: Check

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  types:
    name: Types
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm check
      - run: pnpm dtslint

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm lint

  test:
    name: Test (${{ matrix.shard }})
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        shard: [1/5, 2/5, 3/5, 4/5, 5/5]
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: |
          pnpm vitest \
            --shard ${{ matrix.shard }} \
            --pool threads \
            --poolOptions.threads.isolate false \
            --poolOptions.threads.useAtomics true \
            --poolOptions.threads.singleThread true
