name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node:
    name: Node
    runs-on: buildjet-32vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - run: pnpm vitest

  bun:
    name: Bun
    runs-on: buildjet-32vcpu-ubuntu-2204
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/actions/setup
      - name: Install bun
        uses: oven-sh/setup-bun@v1
      - run: bun vitest
